insert into item values(1, 'ペン', 150, 'CD-A01', CURRENT_DATE(), 0);
insert into item values(2, 'ノート', 210, 'CD-A01', CURRENT_DATE(), 0);
insert into item values(3, 'コンパス', 350, 'CD-A01', CURRENT_DATE(), 0);
insert into item values(4, '消しゴム', 100, 'CD-A01', CURRENT_DATE(), 0);
insert into item values(5, 'えんぴつ', 80, 'CD-A01', CURRENT_DATE(), 0);
insert into item values(6, '筆箱', 1000, 'CD-A01', CURRENT_DATE(), 0);
insert into item values(7, 'ペン', 150, 'CD-A01', CURRENT_DATE(), 0);
insert into item values(8, 'ノート', 210, 'CD-A01', CURRENT_DATE(), 0);
insert into item values(9, 'コンパス', 350, 'CD-A01', CURRENT_DATE(), 0);
insert into item values(10, '消しゴム', 100, 'CD-A01', CURRENT_DATE(), 0);
insert into item values(11, 'えんぴつ', 80, 'CD-A01', CURRENT_DATE(), 0);
insert into item values(12, '筆箱', 1000, 'CD-A01', CURRENT_DATE(), 0);
insert into loginuser values('root', 'root', 'DATA_MANAGER');
insert into loginuser values('user', 'user', 'USER');
insert into loginuser values('yanagawa', '123456', 'USER');
